- name: Raspberry Pi Updates
  hosts: all
  tasks:
    - name: Update apt packages
      become: true
      command: apt update

    - name: Upgrade apt packages
      become: true
      command: apt upgrade -y

    - name: Remove old packages
      become: true
      command: apt autoremove -y

    - name: Update tzdata
      become: true
      command: dpkg-reconfigure --frontend noninteractive tzdata
