- name: Search for Windows updates asynchronously
  hosts: all
  win_updates:
    category_names:
    - SecurityUpdates
    - CriticalUpdates
    - UpdateRollups
    state: searched
  reboot: yes
  async: 180
  poll: 10
  become: yes
  become_method: runas
  become_user: SYSTEM
