- name: Search-only, return list of updates found (if any)
  win_updates:
    category_names:
     -SecurityUpdates
     -CriticalUpdates
     -UpdateRollups
    state: searched
  register: updates_found

- name: display found updates
  debug:
    msg: "{{ updates_found }}"
